name: Claude Code

on:
    issue_comment: { types: [created] }
    pull_request_review_comment: { types: [created] }
    workflow_dispatch:

permissions:
    id-token: write
    contents: write
    pull-requests: write
    issues: write

jobs:
    claude:
        runs-on: ubuntu-latest
        steps:
            - uses: anthropics/claude-code-action@v1
              with:
                  anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
                  claude_args: "--max-turns 5"
